# Site settings
title: Maurits Dekkers
email: me@maurits.io
phone: +31 (0)6 27 235 268
description: > # this means to ignore newlines until "baseurl:"
  I'm a web developer living and working in the Amsterdam area. I have 10 years
  experience in developing and managing the development of web applications in
  Drupal, Symfony, Zend Framework, and AngularJS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maurits.io" # the base hostname & protocol for your site
twitter_username: mauzeh
github_username:  mauzeh

# Build settings
markdown: kramdown
